DEEPSEEK_API_URL = "https://api.deepseek.com/chat/completions"

FAST_MODEL = "deepseek-v4-flash"
REPORT_MODEL = "deepseek-v4-pro"

MAX_MATERIAL_CHARS = 50000
MAX_SEARCH_QUERIES = 8
REGIONAL_MAX_SEARCH_QUERIES = 8
SEARCH_RESULTS_PER_QUERY = 3
SEARCH_PAGES_PER_QUERY = 1
SEARCH_PAGE_TEXT_CHARS = 2500

OSM_NOMINATIM_URL = "https://nominatim.openstreetmap.org/search"
MAP_MAX_REFERENCE_POINTS = 3
MAP_MAX_DEMAND_POINTS = 8
MAP_REQUEST_DELAY_SECONDS = 1.0
MAP_GEOCODE_TIMEOUT_SECONDS = 12

OCR_WORKERS = 2
OCR_MIN_IMAGE_PIXELS = 160000
OCR_MAX_IMAGES_PER_PAGE = 4
OCR_MAX_IMAGES_PER_FILE = 80
OCR_MAX_RENDERED_PDF_PAGES = 80
OCR_RENDERED_PDF_PAGE_SIZE = 2200
OCR_SPARSE_PAGE_CHARS = 120

SUPPORTED_EXTENSIONS = [
    ".ppt",
    ".pptx",
    ".pdf",
    ".docx",
    ".png",
    ".jpg",
    ".jpeg",
]
